controller_list:
  - name: fake_arm_controller
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
  - name: fake_eef_controller
    joints:
      - bh_j11_joint
      - bh_j12_joint
      - bh_j22_joint